export const BUSINESS_DASHBOARD_SCREEN = 'Business Dashboard'
export const FACULTY_DASHBOARD_SCREEN = 'Faculty Dashboard'
export const STUDENT_DISCUSSION_DASHBOARD_SCREEN = 'Student Discussion Dashboard'
export const NOTIFICATION_SCREEN = 'Notification'
export const CONVERSATION_SCREEN = 'Conversation'
export const SEACRH_SCREEN = 'Search'
export const ACTIVE_CONVERSATION_TAB = 'Active conversation tab'
export const ALL_CONVERSATION_TAB = 'All conversation tab'
