export const TEXT_AVAILABLE = 'Khả dụng'
export const TEXT_SEE_MORE = 'xem thêm'
export const TEXT_HIDE_LESS = 'ẩn bớt'
export const TEXT_LIKE_BY = 'Thích bởi'
export const TEXT_REPLY = 'Trả lời'
export const TEXT_DELETE = 'Xóa'
export const TEXT_SEE_MORE_COMMENTS = 'Xem thêm bình luận';
export const TEXT_HIDDEN_COMMENTS = 'Ẩn bớt bình luận';
export const TEXT_TITLE_COMMENT = 'Bình luận';
export const TEXT_COMPLETE = 'Hoàn tất'
export const TEXT_TITLE = 'Thêm bài viết'
export const TEXT_INPUT_PLACEHOLDER = 'Hãy nhập nội dung bài viết.'
export const TEXT_PLACEHOLDER_INPUT_COMMENT = 'Hãy nhập nội dung bình luận.'
export const TEXT_ADD_IMAGES = 'Thêm hình ảnh'
export const TEXT_WARNING_IMAGE_ERROR = 'Không thể hiển thị hình ảnh'
export const TYPE_POST_BUSINESS = 'doanh-nghiep';
export const TYPE_POST_FACULTY = 'khoa';
export const TYPE_POST_STUDENT = 'sinh-vien';
export const NAME_GROUP = 'Group by TDC - Trường Cao Đẳng Công Nghệ Thủ Đức';
export const TEXT_AGREE = 'Đồng ý'
export const TEXT_CANCEL = 'Hủy'
export const TEXT_NOTIFYCATIONS = 'Thông báo'
export const TEXT_WARNING = 'Cảnh báo'
export const TEXT_DETAILED_WARNING_CONTENT_NULL = 'nội dung bài viết không thể để trống'
export const TEXT_DETAILED_WARNING_CONTENT_NUMBER_LIMITED = 'số  lượng ký tự không được vượt quá'
export const TEXT_DEFINITE_QUESTION = 'Bạn có thực sự muốn xóa bức ảnh này chứ'
export const TEXT_CREATE_POST_SUCCESS = 'Đã tạo bài viết thành công'
export const TEXT_CREATE_POST_FAIL = 'Tạo bài viết không thành công'
export const TEXT_CHAR = 'ký tự';
export const TEXT_WARNING_CREATE_COMMENT_FAIL = 'Tạo bình luận thất bại';
export const TEXT_WARNING_CONTENT_COMMENT_NULL = 'nội dung bình luận không thể để trống';
export const TEXT_WARNING_CONTENT_COMMENT_NUMBER_LIMITED = 'nội dung bình luận không thể quá'; 