import { SPLASH_SCREEN, TOP_TAB_NAVIGATOR, LOGIN_SCREEN, IMAGE_VIEW_SCREEN, CREATE_SURVEY_SCREEN } from './Screen'

export const INITIAL_SCREEN = SPLASH_SCREEN
export const SERVER_ADDRESS = 'http://192.168.1.7:8080/'
