import { LOGIN_SCREEN, STUDENT_REGISTER_SCREEN, TOP_TAB_NAVIGATOR,BUSINESS_REGISTER_SCREEN, MESSENGER_SCREEN, CREATE_RECRUITMENT_SCREEN } from "./Screen";

export const INITIAL_SCREEN = CREATE_RECRUITMENT_SCREEN
