export const REGISTER_SUCCESS =  'resgister_success'
export const CHANGE_PASSWORD_SUCCESS =  'change_password_success'
export const UPDATE_POST =  'update_post'
export const CREATE_SURVEY =  'create_survey'
export const SAVE_POST =  'save_post'
export const USER_LIKE_POST =  'user_like_post'
export const USER_COMMENT_POST =  'user_comment_post'
export const USER_REPLY_COMMENT =  'user_reply_comment'
export const USER_CONDUCT_SURVEY =  'user_conduct_survey'
export const POST_LOG =  'post_log'
export const ACCEPT_POST =  'accept_post'
export const USER_UPDATE =  'user_update'
export const USER_FOLLOW =  'user_follow'
export const USER_CHANGE_LANGUAGE =  'user_change_language'
export const USER_APPLY_JOB =  'user_apply_job'
export const USER_CREATE_WATCH_JOB =  'user_create_watch_job'

