export const LIKE_ACTION = 0
export const COMMENT_ACTION = 1
export const SHOW_LIST_USER_REACTED = 2
export const GO_TO_PROFILE_ACTIONS = 0
export const GO_TO_MENU_ACTIONS = 0
export const NUMBER_MAX_CHARACTER = 1024
export const NUMBER_MIN_CHARACTER = 0
export const TYPE_NORMAL_POST = 'thong-thuong'
export const TYPE_RECRUITMENT_POST = 'tuyen-dung'
export const TYPE_SURVEY_POST = 'khao-sat'
export const TYPE_NORMAL_POST_TEXT = 'Thông thường';
export const TYPE_RECRUITMENT_POST_TEXT = 'Tuyển dụng';
export const TYPE_SURVEY_POST_TXT = 'Khảo sát';
export const CALL_ACTION = 0;
export const FOLLOW_ACTION = 1;
export const MESSENGER_ACTION = 2;
export const MENU_CLICK_ACTION = 3;
export const SEE_BACKGROUND = 0;
export const SEE_AVATAR = 1;
export const CLICK_CAMERA_AVATAR_EVENT = 2;
export const CLICK_CAMERA_BACKGROUND_EVENT = 3;
