export const LIKE_ACTION = 0
export const COMMENT_ACTION = 1
export const SHOW_LIST_USER_REACTED = 2
export const GO_TO_PROFILE_ACTIONS = 0
export const GO_TO_MENU_ACTIONS = 0
export const NUMBER_MAX_CHARACTER = 1024
export const NUMBER_MIN_CHARACTER = 0
export const TYPE_NORMAL_POST = 'thong-thuong'
export const TYPE_RECRUITMENT_POST = 'tuyen-dung'
export const TYPE_SURVEY_POST = 'khao-sat'
export const CLICK_UN_SAVE_POST = 4;
export const CLICK_UPDATE_POST = 5;
export const FacultyOfElectricalEngineering = "Khoa điện - Điện tử";
export const FacultyOfInformationTechnology = "Khoa Công Nghệ Thông Tin";
export const FacultyOfAutomationTechnology = "Khoa Công Nghệ Tự Động";
export const FacultyOfMechanicalEngineeringAndManufacturing = "Khoa Cơ Khí Chế Tạo Máy";
export const AutomobileEngineeringDepartment = "Khoa Cơ Khí Ô Tô";
export const FacultyOfFinanceAndAccounting = "Khoa Tài Chính - Kế Toán";
export const FacultyOfBusinessAdministration = "Khoa Quản Trị Kinh Doanh";
export const FacultyOfTourism = "Khoa Du Lịch";
export const DepartmentOfEnglish = "Khoa Tiếng Anh";
export const DepartmentOfKoreanLanguage = "Khoa Tiếng Hàn";
export const JapaneseLanguageDepartment = "Khoa Bộ Môn Tiếng Nhật"
export const groupStudent = 'group_tdc';
export const groupBusiness = 'group_connect_business';
export const postHasActive = 1;
export const TYPE_POST_BUSINESS = 'doanh-nghiep';
export const TYPE_POST_FACULTY = 'khoa';
export const TYPE_POST_STUDENT = 'sinh-vien';
export const TYPE_POST_NORMAL = 'thong-thuong';
export const TYPE_NORMAL_POST_TEXT = 'Thông thường';
export const TYPE_RECRUITMENT_POST_TEXT = 'Tuyển dụng';
export const TYPE_SURVEY_POST_TXT = 'Khảo sát';
export const CALL_ACTION = 0
export const FOLLOW_ACTION = 1
export const MESSENGER_ACTION = 2
export const MENU_CLICK_ACTION = 3
export const SEE_BACKGROUND = 0
export const SEE_AVATAR = 1
export const CLICK_CAMERA_AVATAR_EVENT = 2
export const CLICK_CAMERA_BACKGROUND_EVENT = 3
export const CLICK_SAVE_POST_EVENT = 0
export const CLICK_DELETE_POST_EVENT = 1
export const CLICK_SEE_RESULT_POST_EVENT = 2
export const CLICK_SEE_LIST_CV_POST_EVENT = 3
export const CONDUCT_MODE = 0
export const EDIT_MODE = 1
export const REVIEW_MODE = 2
